### ISSUE TITLE
Trackmania Script suffering from many bugs

### ISSUE THREAD

**Issue by Rastats** [Voxelse/ASLScripts#13]
Following the recent update of the script, we've encountered several bugs.

I made a video compilation of all the bugs I encountered, you can find it here : https://www.youtube.com/watch?v=QTx-rcMIE0o
I first used the checkpoint and finish splits and tried to see how the script reacted to leaving maps before finishing them.
Following that I did a normal Track Of The Day speedrun with finish splits only and I still faced the same bugs.

However I had no problem with a speedrun of the Training campaign with finish splits activated.

Speedself also encountered issues during a Winter 2021 (seasonal campaign) speedrun :
https://clips.twitch.tv/EndearingWiseTapirAMPEnergy-yIlMsOdTcCmmjBDJ
https://clips.twitch.tv/SmoggyBillowingBaboonTebowing-VzhlRgTRLmTai48e

Here are the log files from all the runs I did :

February 2021 TOTD - only some tracks were completed : https://pastebin.com/uZeNgRxZ

July 2020 TOTD - speedrun done normally (all tracks completed) : https://pastebin.com/Rm9Day5h

Training - speedrun with no script bug as far as I remember : https://pastebin.com/5Ndyya4v

**Comment by Voxelse** [comment]
Indeed it seems that the race data behavior has changed which causes garbage reading.
I've fixed that in https://github.com/Voxelse/ASLScripts/commit/46cbfcb5bc9c50db5222b4c9c6dfec413477e546 which should fix all the issues but let me know if any remain.
