### ISSUE TITLE
Incorrect game time and last split not happening

### ISSUE THREAD

**Issue by IKLProject** [Voxelse/ASLScripts#14]
The game time bug is very similar to the bugs faced on the previous version : https://www.twitch.tv/videos/978723899

The last split bug happened to the same runner on multiple of his speedruns : https://www.speedrun.com/tm/run/ylogq9xy

**Comment by Voxelse** [comment]
Fixed in 80c0f057f1aaf82d1ca3846e0a296cc34616f111
