### ISSUE TITLE
Action Henk autosplitter only splits each batch once

### ISSUE THREAD

**Issue by badBlackShark** [Voxelse/ASLScripts#4]
As I saw, basically all of the autosplitter was rewritten. I did some 100% runs with it, and during one session it only splits each batch once. It only works again when you restart (idk if game or LiveSplit, I just did both).

E.g. you reset after The Classic, then the Back in Action split will not work anymore, but all others will.

**Comment by Voxelse** [comment]
Oh yeah, you're right.
Actually, the array used to store the medals doesn't get reset when the timer restart so that's why.
I've fixed the issue and refactored the vars initialization a bit. Tell me if it fixes it on your side so I can close the issue.
Sorry for the inconvenience.

**Comment by badBlackShark** [comment]
This appears to be fixed :)
